### ISSUE TITLE
Home keeps disappearing

### ISSUE THREAD

**Issue by ablos** [Gunpowder-MC/GunpowderTeleport#12]
When using /sethome without a name, the home keeps disappearing after server reboot. Error:
[13:37:08] [Gunpowder Database Thread/ERROR]: Error on Database Thread! Please report to the mod author if this is unexpected!
org.jetbrains.exposed.exceptions.ExposedSQLException: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: Home.owner, Home.homeName)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:29) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.QueriesKt.insert(Queries.kt:70) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at io.github.gunpowder.modelhandlers.HomeHandler$newHome$2.invoke(HomeHandler.java:99) ~[gunpowder-teleport-1.0.4+gunpowder.0.4.1.mc.1.16.5.jar:?]
        at io.github.gunpowder.modelhandlers.HomeHandler$newHome$2.invoke(HomeHandler.java:40) ~[gunpowder-teleport-1.0.4+gunpowder.0.4.1.mc.1.16.5.jar:?]
        at io.github.gunpowder.entities.GunpowderDatabase$databaseThread$1$value$1.invoke(GunpowderDatabase.java:53) ~[gunpowder-base-0.4.2+1.16.5.jar:?]
        at io.github.gunpowder.entities.GunpowderDatabase$databaseThread$1$value$1.invoke(GunpowderDatabase.java:52) ~[gunpowder-base-0.4.2+1.16.5.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:191) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:190) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at io.github.gunpowder.entities.GunpowderDatabase$databaseThread$1.invoke(GunpowderDatabase.java:52) [gunpowder-base-0.4.2+1.16.5.jar:?]
        at io.github.gunpowder.entities.GunpowderDatabase$databaseThread$1.invoke(GunpowderDatabase.java:44) [gunpowder-base-0.4.2+1.16.5.jar:?]
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) [420d3c92-4482-474d-ba2a-9936668868da.jar:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (UNIQUE constraint failed: Home.owner, Home.homeName)
        at org.sqlite.core.DB.newSQLException(DB.java:941) ~[8832d794-ef77-43ba-b34b-b347d3da8bdb.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:953) ~[8832d794-ef77-43ba-b34b-b347d3da8bdb.jar:?]
        at org.sqlite.core.DB.execute(DB.java:854) ~[8832d794-ef77-43ba-b34b-b347d3da8bdb.jar:?]
        at org.sqlite.core.DB.executeUpdate(DB.java:895) ~[8832d794-ef77-43ba-b34b-b347d3da8bdb.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102) ~[8832d794-ef77-43ba-b34b-b347d3da8bdb.jar:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:23) ~[f4869db9-d9f6-458e-bae0-815c46595169.jar:?]
        at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:111) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:117) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:11) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61) ~[030674d3-fa9a-4a01-88d8-d6f65f57e51d.jar:?]
        ... 20 more

**Comment by Martmists-GH** [comment]
I just figured out I was placing the fix in the wrong place, give me some time to fix this (~24H)
