### ISSUE TITLE
[BUG] MySQL Crashing

### ISSUE THREAD

**Issue by TheRealM18** [Gunpowder-MC/GunpowderTeleport#7]
When using MySQL option in Gunpowder, and trying to load the Teleport option, it fails to load with this error.

at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998) ~[b320830c-e827-4881-b345-b052ad2cd02f.jar:?]
at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:23) ~[643a5c33-e509-4238-ba37-77163b3df3df.jar:?]
at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:93) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:126) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:112) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:88) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:79) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.SchemaUtils.execStatements(SchemaUtils.kt:175) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns(SchemaUtils.kt:236) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns$default(SchemaUtils.kt:229) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at io.github.gunpowder.entities.GunpowderRegistry$registerTable$1.invoke(GunpowderRegistry.java:88) ~[gunpowder-base-0.2.10+1.16.2.jar:?]
at io.github.gunpowder.entities.GunpowderRegistry$registerTable$1.invoke(GunpowderRegistry.java:52) ~[gunpowder-base-0.2.10+1.16.2.jar:?]
at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104) ~[083567af-ec12-4496-bcda-411b454db50d.jar:?]
at io.github.gunpowder.entities.GunpowderRegistry.registerTable(GunpowderRegistry.java:87) ~[gunpowder-base-0.2.10+1.16.2.jar:?]
at io.github.gunpowder.GunpowderTeleportModule.onInitialize(GunpowderTeleportModule.java:69) ~[gunpowder-teleport-1.0.0+gunpowder.0.2.9.mc.1.16.2.jar:?]
at io.github.gunpowder.mod.AbstractGunpowderMod.initialize(AbstractGunpowderMod.java:77) ~[gunpowder-base-0.2.10+1.16.2.jar:?]
at io.github.gunpowder.mod.server.GunpowderServerMod.onInitializeServer(GunpowderServerMod.java:43) ~[gunpowder-base-0.2.10+1.16.2.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
... 17 more

**Comment by Martmists-GH** [comment]
This is not a complete error log. Please post a full crash report instead. Make sure to post it on a site like pastebin, hastebin or similar.

**Comment by TheRealM18** [comment]
[2020-10-01-3.log](https://github.com/Gunpowder-MC/GunpowderTeleport/files/5323326/2020-10-01-3.log)

I have to crash the server to disable the server from hanging from it.  To fix it all i have to do is disable the Teleport module

**Comment by Martmists-GH** [comment]
install PlayerAbilityLib

**Comment by TheRealM18** [comment]
PlayerAbilityLib 1.2.0 and 1.2.1 does not fix this problem... unless there is a different one then curseforge can find.

**Comment by Martmists-GH** [comment]
`Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'name' used in key specification without a key length`

We've been getting more and more issues with MySQL, and we should look into whether we should make changes keep supporting it or drop it entirely.
